version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cdc-registration-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lolf8bz4v55j"
s3_prefix = "cdc-registration-demo"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
